hmpps.sqs:
  provider: localstack
  queues:
    domainevents:
      queueName: rp_api_queue
      dlqName: rp_api_dlq
      subscribeTopicId: domaineventsqueue
  topics:
    domaineventsqueue:
      arn: arn:aws:sns:eu-west-2:000000000000:domain_events_queue
    domaineventsoutbound:
      arn: arn:aws:sns:eu-west-2:000000000000:domain_events_outbound
