hmpps.sqs:
  provider: localstack
  queues:
    offenderevents:
      queueName: rp_api_queue
      dlqName: rp_api_dlq
      subscribeTopicId: offendereventsqueue
  topics:
    offendereventsqueue:
      arn: arn:aws:sns:eu-west-2:000000000000:offender_events_queue
    domaineventsoutbound:
      arn: arn:aws:sns:eu-west-2:000000000000:domain_events_outbound
