version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.8


executors:
  integration-tests:
    docker:
      - image: cimg/openjdk:16.0
      - image: circleci/postgres:13.2
        environment:
          - POSTGRES_PASSWORD=test
          - POSTGRES_USER=test
          - POSTGRES_DB=restricted-patients-api-db
    environment:
      _JAVA_OPTIONS: -Xmx256m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=1
    working_directory: ~/app


jobs:
  validate:
    executor: integration-tests
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          name: Wait for Postgres to be ready
          command: ./postgres-check.sh
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }} 
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
  #      - request-preprod-approval:
  #          type: approval
  #          requires:
  #            - deploy_dev
  #      - hmpps/deploy_env:
  #          name: deploy_preprod
  #          env: "preprod"
  #          context:
  #            - hmpps-common-vars
  #            - hmpps-restricted-patients-api-preprod
  #          requires:
  #            - request-preprod-approval
  #      - request-prod-approval:
  #          type: approval
  #          requires:
  #            - deploy_preprod
  #      - hmpps/deploy_env:
  #          name: deploy_prod
  #          env: "prod"
  #          slack_notification: true
  #          context:
  #            - hmpps-common-vars
  #            - hmpps-restricted-patients-api-prod
  #          requires:
  #            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          context:
            - hmpps-common-vars
            - veracode-credentials


