version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@5.2.0

# We provide a custom setup as the java_localstack_postgres orb does not allow us to specify a DB name
# orbs:
#   hmpps: ministryofjustice/hmpps@5.2.3
# jobs:
#   validate:
#     executor:
#       name: hmpps/java_localstack_postgres
#       jdk_tag: "17.0"
#       localstack_tag: "0.14.0"
#       postgres_tag: "13.2"
#       postgres_password: "test"
#       postgres_username: "test"
executors:
  integration-tests:
    docker:
      - image: cimg/openjdk:18.0
        environment:
          - TZ=Europe/London
      - image: localstack/localstack:0.14.0
        environment:
          - DEBUG=${DEBUG- }
          - DATA_DIR=/tmp/localstack/data
          - SERVICES=sqs,sns
          - DATA_DIR=/tmp/localstack/data
          - DOCKER_HOST=unix:///var/run/docker.sock
          - DEFAULT_REGION=eu-west-2
      - image: circleci/postgres:13.2
        environment:
          - POSTGRES_PASSWORD=test
          - POSTGRES_USER=test
          - POSTGRES_DB=restricted-patients-api-db
    environment:
      _JAVA_OPTIONS: -Xmx256m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-XX:+UseContainerSupport -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=2
    working_directory: ~/app


jobs:
  validate:
    executor: integration-tests
    steps:
      - run: apt update && apt install tzdata -y
      - run:
          command: |
            while true; do
              sleep 5
              ps auxwwf
              echo "======"
            done
          background: true
      - checkout
      - hmpps/wait_till_ready
      # Replace the next lines and .sh file with the following if/when we get the orb working
      # - hmpps/wait_till_ready_postgres
      - run:
          name: Wait for Postgres to be ready
          command: ./postgres-check.sh
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }} 
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - hmpps-restricted-patients-api-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context:
            - hmpps-common-vars
            - hmpps-restricted-patients-api-prod
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "50 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      #- hmpps/veracode_pipeline_scan:
      #    context:
      #      - hmpps-common-vars
      #      - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "19 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars


