apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmppps-restricted-patients-api-queue-housekeeping
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          ttlSecondsAfterFinished: 345600
          containers:
            - name: housekeeping
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPUT http://hmpps-restricted-patients-api/queue-admin/retry-all-dlqs
          restartPolicy: Never
