apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmppps-restricted-patients-api-past-date-check
spec:
  schedule: "0 3 * * *"
  suspend: true
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: past-date-check
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 http://hmpps-restricted-patients-api/process-past-date-restricted-patients
          restartPolicy: Never
