apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmppps-restricted-patients-api-dlq-retry
spec:
  schedule: "{{ .Values.cron.retry_dlqs_schedule }}"
  suspend: true
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: housekeeping
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPUT http://hmpps-restricted-patients-api/queue-admin/retry-all-dlqs
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
