---
# Per environment values which override defaults in hmpps-restricted-patients-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: restricted-patients-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    PRISON_API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-offender-search-preprod.prison.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod

environment: preprod