---
# Per environment values which override defaults in hmpps-restricted-patients-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: restricted-patients-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    PRISON_API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

  allowlist: null

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: digital-prison-service-dev
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-dev-restricted_patients_queue"
    - "Digital-Prison-Services-dev-restricted_patients_queue_dl"
    - "Digital-Prison-Services-dev-rp_queue_for_domain_events"
    - "Digital-Prison-Services-dev-rp_queue_for_domain_events_dl"

environment: dev
