---
# Per environment values which override defaults in hmpps-restricted-patients-api/values.yaml

generic-service:

  ingress:
    host: restricted-patients-api.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    PRISON_API_ENDPOINT_URL: https://prison-api.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-search.prison.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rp-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rp-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  rdsAlertsDatabases:
    cloud-platform-d43cc21ae1d14deb: "Restricted Patients API"
  sqsNumberAlertQueueNames:
    - "dps-core-prod-restricted_patients_queue"
    - "dps-core-prod-restricted_patients_queue_dl"
    - "dps-core-prod-rp_queue_for_domain_events"
    - "dps-core-prod-rp_queue_for_domain_events_dl"

environment: prod
