---
# Per environment values which override defaults in hmpps-restricted-patients-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: restricted-patients-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    PRISON_API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_ENDPOINT_URL: https://prisoner-offender-search-preprod.prison.service.justice.gov.uk
    COMMUNITY_API_ENDPOINT_URL: https://community-api.pre-prod.delius.probation.hmpps.dsd.io
    CASENOTES_API_ENDPOINT_URL: https://preprod.offender-case-notes.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: digital-prison-service-dev
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-preprod-restricted_patients_queue"
    - "Digital-Prison-Services-preprod-restricted_patients_queue_dl"
    - "Digital-Prison-Services-preprod-rp_queue_for_domain_events"
    - "Digital-Prison-Services-preprod-rp_queue_for_domain_events_dl"

environment: preprod
