---
# Per environment values which override defaults in hmpps-restricted-patients-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: dev.hmpps-restricted-patients-api.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
